### ISSUE TITLE
Error compiling LoRaSniffer code

### ISSUE THREAD

**Issue by c4nh0t0** [ElectronicCats/CatWAN_USB_Stick#12]
Hey folks, I'm having an issue while trying to compile the LoRaSniffer.ino code and I'm having those issues as shown in print screen

![image](https://user-images.githubusercontent.com/8462973/204069184-ce7a3177-e042-4d64-8c71-059348d85622.png)

I have all libraries installed (LoRa, ElectronicaCats, SerialCommand). Do you folks have any clue about this?
Thanks!

**Comment by REGIOIGER** [comment]
Hi c4nh0t0, are you using the SerialCommand kroimon library?
https://github.com/kroimon/Arduino-SerialCommand

**Comment by c4nh0t0** [comment]
I don't think so. I'm using SerialCommand library by Hugo Arganda and Daniel Castellon, installed directly by Arduino IDE Library Manager.
![image](https://user-images.githubusercontent.com/8462973/204164599-b0bf5403-6594-4f7f-aace-e1801cf52b8b.png)

**Comment by REGIOIGER** [comment]
Please, use the https://github.com/kroimon/Arduino-SerialCommand library, unistall SerialCommand library by Hugo Arganda and Daniel Castellon first, tell me if works

**Comment by c4nh0t0** [comment]
It worked! Awesome mate.
Many thanks.
