### ISSUE TITLE
help

### ISSUE THREAD

**Issue by S5647787** [ElectronicCats/CatWAN_USB_Stick#20]
hi 
After uploading my code, I get this information, but I can't find other devices that are in 868 Hz frequency. Can you tell me what changes I need to make for this, or did I do a part of the steps wrong?

Welcome to the LoRa Sniffer CLI 0.2v
09:53:03.461 -> 
09:53:03.461 -> With this sketch you can scan the LoRa spectrum
09:53:03.461 -> Changing the Frequency, Spreading Factor, BandWidth or the IQ signals of the radio.
09:53:03.461 -> Type help to get the available commands.
09:53:03.461 -> Electronic Cats ® 2020

**Comment by AndreaZGuz** [comment]
Hi @S5647787 !

Thank you for reaching us again.

CatWAN USB Stick helps you to sniff LoRa packets, but it will not show you exactly the devices working in a specific frequency.

If you want to sniff packets, you need to type "set_rx" in the terminal and CatWAN USB Stick will wait for packets to show them in the terminal.
If you want to change the settings of the communication or monitor the parameters set, type "help" in the terminal to see all the available commands.

[Here](https://github.com/ElectronicCats/CatWAN_USB_Stick/wiki/5.-Examples#using-lora-sniffer-tool) is the explanation for using the "set_rx" command to sniff LoRa packets.

I hope the information helps!
If you have further questions, feel free to write to us again.

**Comment by S5647787** [comment]
thanks for answering
