### ISSUE TITLE
error

### ISSUE THREAD

**Issue by S5647787** [ElectronicCats/CatWAN_USB_Stick#21]
hello. I did all the steps to install the board and port, but I get this error, can you help me?

serial manitor: 16:04:42.756 -> Start ScanNetworks on SAMD Zero 16:04:42.756 -> WiFiNINA_Generic v1.8.15-1 16:08:46.166 ->  16:08:46.166 -> Start ScanNetworks on SAMD Zero 16:08:46.166 -> WiFiNINA_Generic v1.8.15-1

output: no device found on COM8
Failed uploading: uploading error: exit status 1

**Comment by AndreaZGuz** [comment]
Hi  @S5647787 !

Are you using Arduino IDE? If so, could you please share a screenshot showing the error message and that you have already selected the board?

Thank you!

**Comment by S5647787** [comment]
It was working properly until yesterday

13:59:07.344 -> Welcome to the LoRa Sniffer CLI 0.2v
13:59:07.344 -> 
13:59:07.344 -> With this sketch you can scan the LoRa spectrum
13:59:07.344 -> Changing the Frequency, Spreading Factor, BandWidth or the IQ signals of the radio.
13:59:07.344 -> Type help to get the available commands.
13:59:07.344 -> Electronic Cats ® 2020



But today I installed the library (wifi nina) and ran this code (#include <WiFi.h>

void setup() {
  Serial.begin(115200);
  delay(1000);
  Serial.println();
  Serial.println("Program start...");

  // Initialize Wi-Fi
  WiFi.begin("YourNetworkSSID", "YourNetworkPassword");
  while (WiFi.status() != WL_CONNECTED) {
    delay(1000);
    Serial.println("Connecting to Wi-Fi...");
  }

  // Print MAC address
  uint8_t mac[6];
  WiFi.macAddress(mac);
  Serial.print("ESP32 MAC Address: ");
  for (int i = 0; i < 6; i++) {
    Serial.print(mac[i], HEX);
    if (i < 5) Serial.print(':');
  }
  Serial.println();
}

void loop() {
  // Your code here
}
)


 and encountered this error

output: no device found on COM8
Failed uploading: uploading error: exit status 1

!
![photo_6003749146458178990_y](https://github.com/ElectronicCats/CatWAN_USB_Stick/assets/153599676/f4ef3f1a-0429-40c1-b99c-0c2dca9d7171)

**Comment by AndreaZGuz** [comment]
Hi @S5647787 !

Thank you for the updates.
Contact us again in case you face again technical issues.
