### ISSUE TITLE
Lack of build instructions

### ISSUE THREAD

**Issue by BatchDrake** [ElectronicCats/CatWAN_USB_Stick#5]
Hi all,

I'm trying to use the LoRa PHY Sniffer example, but I'm having trouble making it work. First of all, after installing the corresponding board description as you suggest in your README, I faced the following build issue:

```
LoRaSniffer:20:27: fatal error: SerialCommand.h: No such file or directory
 #include <SerialCommand.h>
```

My guess was that it depended on `SerialCommand`, but this library does not show up in the library manager. I looked it up on GitHub and, after finding multiple mutually-incompatible implementations of the same library, I came across this one (https://github.com/kroimon/Arduino-SerialCommand) which seemed to build. The problem now is that LoRaSniffer does not get past these lines:

```c++
void setup(){  
  pinMode(LED_BUILTIN,OUTPUT);      // Configure the onboard LED for output
  digitalWrite(LED_BUILTIN,LOW);    // default to LED off
  pinMode(RFM_DIO5,INPUT);
  Serial.begin(115200); 
  while (!Serial);
```

which don't seem to be related to `SerialCommand` at all. I know the bootloader works because if I set the `LED_BUILTIN` to `HIGH` right before initializing the serial, the green LED lights it up. However, if I set it right after the `while(!Serial)`, the LED remains switched off.

I think I may be missing a primary source of documentation here. The only thing I need is to read the contents of the LoRa PHY frames from Putty, that would be pretty much it. Is there a guide somewhere with detailed steps on how to build & use this sniffer?

Thanks!

**Comment by sabas1080** [comment]
Hi @BatchDrake 

`  while (!Serial);`

wait for serial port to open via Arduino IDE or Putty, after that you would see 

```
  Serial.println("Welcome to the LoRa Sniffer CLI " + String(fwVersion,1) + "v\n");
  Serial.println("With this sketch you can scan the LoRa spectrum");
  Serial.println("Changing the Frequency, Spreading Factor, BandWidth or the IQ signals of the radio.");
  Serial.println("Type help to get the available commands.");
  Serial.println("Electronic Cats ® 2020");
```
if you don´t open serial port, the program will not advance

**Comment by BatchDrake** [comment]
Waited for minutes with no results. Pressing Enter or typing `help` didn't
work either. Port speed was 115200.

**Comment by sabas1080** [comment]
You have to active in serial monitor New Line and carriage Return and send command "help please"

<img width="1327" alt="Captura de Pantalla 2020-06-12 a la(s) 12 49 51" src="https://user-images.githubusercontent.com/2874292/84532121-4d085c00-acab-11ea-9d9b-f1e691b0bc5f.png">

**Comment by BatchDrake** [comment]
Okay, it works now. Thanks!
