### ISSUE TITLE
no 3.3V output and bootloader issue(not sure)

### ISSUE THREAD

**Issue by vileer** [ElectronicCats/CatWAN_USB_Stick#6]
I am trying to make my own board with the USB type-c connector but it didn't work, after review the hw design, I found the AP2112k-3.3 EN pin does not connect to the hight voltage which means no 3.3v output. After I connect the EN pin to VBUS, led lights up and able to program the bootloader. The official catwan stick I bought from tindie didn't have this issue.

But here comes the new problem, after flash the bootloader and plug it into the pc, nothing happens no USB-Serial port show in the Arduino IDE.

**Comment by sabas1080** [comment]
Hi @vileer 

it seems this change I don't update, we have repaired the LDO.

About the bootloader, are you pressing the reset button twice quickly and going into boot mode?

**Comment by vileer** [comment]
@sabas1080 Yes, I did double click the reset button quickly, but nothing happens.

**Comment by vileer** [comment]
Here is my fuses setting, may that help you to diagnos the problem：
SERIAL_NUMBER_3 = 0x41F61D1A
SERIAL_NUMBER_0 = 0x51514B32
SERIAL_NUMBER_1 = 0x53202020
SERIAL_NUMBER_2 = 0xFF07392C
ADC_LINEARITY_0 = 0x08
ADC_LINEARITY_1 = 0x04
ADC_BIASCAL = 0x03
OSC32K_CAL = 0x32
USB_TRANSN = 0x09
USB_TRANSP = 0x19
USB_TRIM = 0x06
DFLL48M_COARSE_CAL = 0x1E
DFLL48M_FINE_CAL = 0x200
ROOM_TEMP_VAL_INT = 0x1E
ROOM_TEMP_VAL_DEC = 0x01
HOT_TEMP_VAL_INT = 0x55
HOT_TEMP_VAL_DEC = 0x00
ROOM_INT1V_VAL = 0xF7
HOT_INT1V_VAL = 0xF4
ROOM_ADC_VAL = 0xAFA
HOT_ADC_VAL = 0xD1E
NVMCTRL_BOOTPROT = SIZE_0BYTES
NVMCTRL_EEPROM_SIZE = SIZE_0BYTES
BOD33USERLEVEL = 0x07
BOD33_EN = ENABLED
BOD33_ACTION = RESET
WDT_ENABLE = DISABLED
WDT_ALWAYSON = DISABLED
WDT_PER = CYC16384
WDT_WINDOW_0 = [X]
WDT_WINDOW_1 = 0x05
WDT_EWOFFSET = CYC16384
WDT_WEN = DISABLED
BOD33_HYST = DISABLED
NVMCTRL_REGION_LOCKS = 0xFFFF

AUX3_WORD_3 = 0x41F61D1A (valid)
AUX3_WORD_16 = 0x51514B32 (valid)
AUX3_WORD_17 = 0x53202020 (valid)
AUX3_WORD_18 = 0xFF07392C (valid)
OTP4_WORD_0 = 0x40004007 (valid)
OTP4_WORD_1 = 0x7B652C9C (valid)
OTP4_WORD_2 = 0xFFFFFE00 (valid)
TEMP_LOG_WORD_0 = 0xF705511E (valid)
TEMP_LOG_WORD_1 = 0xD1EAFAF4 (valid)
USER_WORD_0 = 0xD8E0C7FF (valid)
USER_WORD_1 = 0xFFFFFC5D (valid)

**Comment by sabas1080** [comment]
which bootloader are you using? Can you show me the schematic of you board?

**Comment by vileer** [comment]
I've tried the [bootloader binary file](https://github.com/ElectronicCats/CatWAN_USB_Stick/blob/master/Fw/bootloader_uf2/bootloader-catwan-usb-stick-v3.4.0-70-g3a14b0b-dirty.bin) and the [bootloader elf format file](https://github.com/ElectronicCats/CatWAN_USB_Stick/blob/master/Fw/bootloader_uf2/bootloader-catwan-usb-stick-v3.4.0-70-g3a14b0b-dirty.elf). I follow this [tutorial](https://learn.adafruit.com/proper-step-debugging-atsamd21-arduino-zero-m0/restoring-bootloader) to flash the bootloader by using the J-Link EDU Mini.
the schematic is based on the master repo and changes the USB type-a connector to the usb-c one.
![image](https://user-images.githubusercontent.com/556826/89406623-05a0c800-d750-11ea-8a29-405d29403cbc.png)

**Comment by sabas1080** [comment]
looks good, It is difficult to know what is happening, but I would verify the following:
- that the device is listed USB, the led should blink slowly once listed
- connection on USB terminals
- the reset button bounces and the device never enters boot mode

**Comment by wero1414** [comment]
Hi @vileer any new on this problem?

**Comment by vileer** [comment]
@wero1414 @sabas1080 the bootloader “issues” solved. Turn out that using the wrong chip, the schematic claim to use the ATSAMD21E15B-AUT as the controller but after check the board I brought from tindie the chip actually is ATSAMD21E18A-U, after changing the chip and reflash the bootloader, the bootloader is recognized by the pc.

**Comment by sabas1080** [comment]
@vileer oh sorry, I going to change chip

**Comment by vileer** [comment]
@sabas1080 it is ok, this the charm of an open-source project we can work together to make it successful.
