### ISSUE TITLE
Protective shell 3D model file

### ISSUE THREAD

**Issue by BG7YWL** [ElectronicCats/CatWAN_USB_Stick#7]
Is the 3D file of this protective case public?
![catwan_usbstick](https://user-images.githubusercontent.com/9145406/91284314-54290b80-e7be-11ea-9880-e6e9444d931b.jpg)
![2018-09-05T18_23_15 438Z-DSC_2038 copia](https://user-images.githubusercontent.com/9145406/91284330-58552900-e7be-11ea-95b6-5810028da8df.jpg)

**Comment by wero1414** [comment]
Hello we dont have the 3D file for the case, cause the manufacturer hasnt publish the 3D file on the link below you will find the description of the case and a 2D PDF with all the measures.

https://www.newageenclosures.com/enclosures/usb-enclosures/mini-remote.php
